apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - vote-hpa.yaml
  - result-hpa.yaml

nameSuffix: -dev

commonLabels:
  environment: dev

replicas:
  - name: vote
    count: 1
  - name: result
    count: 1

images:
  - name: anik1999/vote-app
    newTag: "5e53bde7e2b407752a262df4dad3263aef5cf52f"
  - name: anik1999/result-app
    newTag: "5e53bde7e2b407752a262df4dad3263aef5cf52f"
